# Generated by Django 5.1.6 on 2025-02-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilityresult',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibilityresult',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
