# Generated by Django 5.1.6 on 2025-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compatibilityresult_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=10)),
                ('unique_subscription_id', models.CharField(max_length=255, unique=True)),
                ('product_id', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('auto_renewing', models.BooleanField(default=True)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('limit', models.IntegerField(default=3)),
            ],
        ),
    ]
