# Generated by Django 5.1.6 on 2025-04-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscriptionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionuser',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
