# Generated by Django 5.1.6 on 2025-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscriptionuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionuser',
            name='auto_renewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionuser',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
