"""
Django settings for lovecompitability project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from django.utils.translation import gettext_lazy as _, get_language
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w0rcbcqw(@0!^yo@2+eh4578x-!@kt!2k-&yug3jhpznxg-s4%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

LANGUAGE_SESSION_KEY = 'django_language'  # Ensure session-based language switching

# LANGUAGES = [
#     ('en', _('English')),
#     ('es', 'Spanish'),
#     ('fr', 'French'),
#     ('de', 'German'),
#     ('ja', 'Japanese'),
#     ('zh-hans', 'Simplified Chinese'),
#     ('zh-hant', 'Traditional Chinese'),
#     ('ko', 'Korean'),
#     ('ru', 'Russian'),
#     ('ar', 'Arabic'),
#     ('pt', 'Portuguese'),
#     ('it', 'Italian'),
#     ('hi', 'Hindi'),
#     ('id', 'Indonesian'),
#     ('tr', 'Turkish'),
#     ('th', 'Thai'),
#     ('vi', 'Vietnamese'),
#     ('ur', 'Urdu'),
#     ('ms', 'Malay'),
#     ('nl', 'Dutch'),
#     ('pl', 'Polish'),
#     ('sv', 'Swedish'),
#     ('no', 'Norwegian'),
#     ('da', 'Danish'),
#     ('cs', 'Czech'),
#     ('hu', 'Hungarian'),
#     ('fi', 'Finnish'),
#     ('he', 'Hebrew'),
#     ('ro', 'Romanian'),
#     ('el', 'Greek'),
#
# ]
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('ko', '한국어'),
    ('ru', 'Русский'),
    ('ar', 'العربية'),
    ('pt', 'Português'),
    ('it', 'Italiano'),
    ('hi', 'हिन्दी'),
    ('id', 'Bahasa Indonesia'),
    ('tr', 'Türkçe'),
    ('th', 'ไทย'),
    ('vi', 'Tiếng Việt'),
    ('ur', 'اردو'),
    ('ms', 'Bahasa Melayu'),
    ('nl', 'Nederlands'),
    ('pl', 'Polski'),
    ('sv', 'Svenska'),
    ('no', 'Norsk'),
    ('da', 'Dansk'),
    ('cs', 'Čeština'),
    ('hu', 'Magyar'),
    ('fi', 'Suomi'),
    ('he', 'עברית'),
    ('ro', 'Română'),
    ('el', 'Ελληνικά'),
]


LOCALE_PATHS = [
    BASE_DIR / "locale",
]

USE_I18N = True
USE_L10N = True

ROOT_URLCONF = 'lovecompitability.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lovecompitability.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'



USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS
SECURE_HSTS_SECONDS = 31536000  # HTTP Strict Transport Security
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to subdomains
SECURE_HSTS_PRELOAD = True  # Preload the HSTS policy


# CORS settings (if using django-cors-headers)
CORS_ALLOWED_ORIGINS = [
    "https://crush-o-meter.com",
]

STRIPE_PUBLISHABLE_KEY = 'pk_test_51IiO7DBH8Pgfzx7JR3sLT5lz3TwoZU9BVonntulHQWbzVWJ2zq6S7Q12C8hlRj7Gdmb1MvgqyR3tzBIH7Efq7Mjl00yuGsZThY'
STRIPE_SECRET_KEY = 'sk_test_51IiO7DBH8Pgfzx7J1Y9m3u2p5097JDmKoSqckPpmOwfdzYGECFcI3PtyUuCaNoh3yroPXxAcsmlMYvsPgPC9VHCD00qm0HMC5P'

# settings.py

try:
    # imp.find_module('local_settings')
    from .local_settings import *
except ImportError:
    print('hayhay')
